# Generated by Django 4.2.6 on 2023-10-21 05:53

import apps.store.models
import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category Name')),
                ('slug', models.SlugField(unique=True)),
                ('seo_text', models.CharField(max_length=255, verbose_name='Category SEO Text')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/%D', verbose_name='Category Banner')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/%D', verbose_name='Category Icon')),
                ('active', models.BooleanField(default=True, verbose_name='Activate Category')),
                ('has_children', models.BooleanField(default=False)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('slug', models.SlugField(unique=True)),
                ('short_description', ckeditor.fields.RichTextField(verbose_name='Short Description')),
                ('image', models.ImageField(upload_to=apps.store.models.upload_product_main_image_path)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Original Price')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='Show product on website')),
                ('quantity', models.IntegerField(verbose_name='Number of products available')),
                ('max_order_count', models.IntegerField(blank=True, null=True, verbose_name='Max cart quantity')),
                ('long_description', ckeditor.fields.RichTextField(verbose_name='Long Description')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Product Rating')),
                ('rating_count', models.IntegerField(default=0, verbose_name='Number of rating')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Rating Value')),
                ('review', models.CharField(blank=True, max_length=20, null=True, verbose_name='Review')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.store.models.upload_product_image_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=15, verbose_name='Label eg Weight')),
                ('value', models.CharField(max_length=100, verbose_name='Value eg 500g')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Additional Information',
            },
        ),
    ]
