# Generated by Django 4.2.6 on 2023-10-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orders_count',
            field=models.IntegerField(default=0, verbose_name='Number ordered'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(verbose_name='Stock'),
        ),
    ]
