# Generated by Django 4.2.6 on 2023-10-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlyoutMenuItems',
            new_name='FlyoutMenuItem',
        ),
        migrations.AlterModelOptions(
            name='flyoutmenuitem',
            options={'verbose_name_plural': 'Flyout Menu'},
        ),
        migrations.AlterModelOptions(
            name='homepageproductfloor',
            options={'verbose_name_plural': 'Homepage ProductFloors'},
        ),
        migrations.AlterModelOptions(
            name='homepageslider',
            options={'verbose_name_plural': 'Homepage Sliders'},
        ),
    ]
