# Generated by Django 4.2.6 on 2023-10-21 07:41

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_flyoutmenuitems_flyoutmenuitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageproductfloor',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='homepageproductfloor',
            name='has_countdown',
            field=models.BooleanField(default=False, verbose_name='Countdown Present'),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='image',
            field=models.ImageField(upload_to=apps.content.models.upload_image_path, verbose_name='Image'),
        ),
    ]
