# Generated by Django 4.2.6 on 2023-10-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_homepageproductfloor_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='landing_page',
            new_name='slug',
        ),
    ]
