# Generated by Django 4.2.6 on 2023-10-21 14:13

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_landing_page_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=apps.content.models.upload_page_image_path),
        ),
    ]
