# Generated by Django 4.2.6 on 2023-10-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_page_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyoutmenuitem',
            name='label',
            field=models.CharField(max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='landing_page',
            field=models.CharField(max_length=255, verbose_name='URL'),
        ),
    ]
