# Generated by Django 4.2.6 on 2023-10-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_flyoutmenuitem_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyoutmenuitem',
            name='landing_page',
            field=models.CharField(max_length=255, verbose_name='URL'),
        ),
    ]
